apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
      - name: mern-frontend
        image: udaybadola/mern-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://mern-backend:5050  # Ensure this points to the backend service name
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend-service
spec:
  selector:
    app: mern-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # This exposes the service externally
